name: nightly-test-run-yuniql-linux-x64-latest

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: trigger netlify build
        run: |
          curl -X POST -d '{}' https://ci.appveyor.com/api/github/webhook?id=v8rycdu2dkcgs1wm
